### ISSUE TITLE
Windows is not supported 

### ISSUE THREAD

**Issue by MomenFathi** [epsylon/cintruder#2]
path structure is only token for UNIX! 

could you please make it cross-platform, thanx

**Comment by epsylon** [comment]
I will add that to my tasks agenda. Thanks for your report...

**Comment by epsylon** [comment]
@MomenFathi On this issue, about which path structure are you talking?.
Can you provide me an example (traceback...) of execution of the tool, at your environment?.
If you are using Win32, you have some code related to work on it. Ex:
https://github.com/epsylon/cintruder/blob/master/core/ocr.py#L139
Isn't that code working?.
