### ISSUE TITLE
Cant install on windows/How to import?

### ISSUE THREAD

**Issue by bondeanikets** [epsylon/cintruder#3]
Seeing the result, I am excited about this library. But, I am not able to install this on my windows 10 (I tried with pip as well as conda). Also curious as to how can this be used in a .py file.

Thanks!

**Comment by epsylon** [comment]
@bondeanikets About which library are you talking about?

**Comment by bondeanikets** [comment]
Apologies for not being clear. I am talking about cintruder.

**Comment by epsylon** [comment]
This tools is using Python. You can execute it on your Win32.
